### ISSUE TITLE
Introduce Alpine as a base image

### ISSUE THREAD

**Issue by pascalandy** [firepress-org/ghostfire#25]
Testing this image

```
edge-3.4.0_2020-02-01_15H02s06_5ed7ce9
```

Dockerfile (branch: edge-alpine)
https://github.com/firepress-org/ghostfire/tree/5ed7ce97f21b4da0a105fd411a59e3eb5d569097

### log

```
10000013-devcerise-ghost.1.s24olwmw3nt1@golf1    | [2020-02-01 21:51:22] INFO Ghost is running in production...
10000013-devcerise-ghost.1.s24olwmw3nt1@golf1    | [2020-02-01 21:51:22] INFO Your site is now available on https://devcerise.site/
10000013-devcerise-ghost.1.s24olwmw3nt1@golf1    | [2020-02-01 21:51:22] INFO Ctrl+C to shut down
10000013-devcerise-ghost.1.s24olwmw3nt1@golf1    | [2020-02-01 21:51:22] INFO Ghost boot 5.752s
10000013-devcerise-ghost.1.s24olwmw3nt1@golf1    | [2020-02-01 21:51:28] INFO "GET /" 301 7ms
10000013-devcerise-ghost.1.s24olwmw3nt1@golf1    | (node:6) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
10000013-devcerise-ghost.1.s24olwmw3nt1@golf1    | [2020-02-01 21:51:32] INFO "HEAD /" 200 687ms
10000013-devcerise-ghost.1.u9az0oz1wxy7@golf3    | events.js:200
10000013-devcerise-ghost.1.u9az0oz1wxy7@golf3    |       throw er; // Unhandled 'error' event
10000013-devcerise-ghost.1.u9az0oz1wxy7@golf3    |       ^
10000013-devcerise-ghost.1.u9az0oz1wxy7@golf3    |
10000013-devcerise-ghost.1.u9az0oz1wxy7@golf3    | Error: EACCES: permission denied, open '/var/lib/ghost/content/logs/https___devcerise_site_production.error.log'
10000013-devcerise-ghost.1.u9az0oz1wxy7@golf3    | Emitted 'error' event on WriteStream instance at:
10000013-devcerise-ghost.1.u9az0oz1wxy7@golf3    |     at internal/fs/streams.js:294:12
10000013-devcerise-ghost.1.u9az0oz1wxy7@golf3    |     at FSReqCallback.oncomplete (fs.js:146:23) {
10000013-devcerise-ghost.1.u9az0oz1wxy7@golf3    |   errno: -13,
10000013-devcerise-ghost.1.u9az0oz1wxy7@golf3    |   code: 'EACCES',
10000013-devcerise-ghost.1.u9az0oz1wxy7@golf3    |   syscall: 'open',
10000013-devcerise-ghost.1.u9az0oz1wxy7@golf3    |   path: '/var/lib/ghost/content/logs/https___devcerise_site_production.error.log'
```

**Comment by pascalandy** [comment]
fixed since 3.30.0
